<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tap to unmute_ytp-cued-thumbnail-overlay-image</name>
   <tag></tag>
   <elementGuidId>399d6874-09ec-4c6c-8d6a-8ad92b359bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ytp-cued-thumbnail-overlay-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ytp-cued-thumbnail-overlay-image</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2df2551-f6e8-4d3a-b67a-e0ca7734ac6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-cued-thumbnail-overlay-image</value>
      <webElementGuid>d6bd4819-739b-4db4-852a-ec80b7a0aaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;ytp-cued-thumbnail-overlay&quot;]/div[@class=&quot;ytp-cued-thumbnail-overlay-image&quot;]</value>
      <webElementGuid>3bd2d913-764d-4e2d-bc64-528702981703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Load Testing Software  No.1 Software P_68ccdd/iframe</value>
      <webElementGuid>0fb4495b-8c66-4b5a-848f-4c0e2cd2b422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div[4]/div</value>
      <webElementGuid>baf97bca-140d-4772-a885-19e9b10c8e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>291a90a3-ed23-486e-805a-3d261b8bf3fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
