<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Services</name>
   <tag></tag>
   <elementGuidId>1b6ebd37-69ab-42e1-bda9-f84bf28d7882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-dropdown-toggle-2']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#w-dropdown-toggle-2 > div:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Services&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d3b4fa7-d473-4f79-932e-e330f8449ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>44d00cba-9921-4560-9691-01ea564311fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-dropdown-toggle-2&quot;)/div[2]</value>
      <webElementGuid>ebda788f-c4f8-4ee0-bab0-34df225221f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-dropdown-toggle-2']/div[2]</value>
      <webElementGuid>34211931-1e2b-42bd-8fc0-cacf8c95fd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transparent, scalable pricing to match your testing needs.'])[1]/following::div[4]</value>
      <webElementGuid>a4c82c5c-c33e-4f0c-9687-fd0699fcc12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::div[5]</value>
      <webElementGuid>4c8a0731-7de3-43fc-890b-81db36077606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service categories'])[1]/preceding::div[2]</value>
      <webElementGuid>64e241f9-73f5-4779-b83a-f48c6845e045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Assurance'])[1]/preceding::div[2]</value>
      <webElementGuid>8b76cb81-7ed7-426b-9cbe-5d75f38e11c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Services']/parent::*</value>
      <webElementGuid>46baa16f-5841-4d8a-ad36-f70540f72945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div[2]</value>
      <webElementGuid>530b9fc0-ae90-4779-877b-d6177e28f66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Services' or . = 'Services')]</value>
      <webElementGuid>e63e633d-c30f-40d7-94aa-8f135f51f58a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
